USE ROLE OPS;
ALTER TASK TASKDB.DWH.POPULATE_FACT_REVENUES RESUME;
ALTER TASK TASKDB.DWH.POPULATE_DIM_REVIEWS_RESULTS RESUME;
ALTER TASK TASKDB.DWH.POPULATE_DIM_MOVIES RESUME;
ALTER TASK TASKDB.DWH.POPULATE_DIM_DISTRIBUTORS RESUME;
ALTER TASK TASKDB.DWH.POPULATE_DIM_MOVIES_REVIEWERS RESUME;
ALTER TASK TASKDB.DWH.POPULATE_DIM_DATES RESUME;
ALTER TASK TASKDB.DWH.DWH_START RESUME;

-- DELETION SECTION
/*
USE ROLE OPS;
ALTER TASK TASKDB.DWH.DWH_START SUSPEND;
ALTER TASK TASKDB.DWH.POPULATE_DIM_DATES SUSPEND;
ALTER TASK TASKDB.DWH.POPULATE_DIM_MOVIES_REVIEWERS SUSPEND;
ALTER TASK TASKDB.DWH.POPULATE_DIM_DISTRIBUTORS SUSPEND;
ALTER TASK TASKDB.DWH.POPULATE_DIM_MOVIES SUSPEND;
ALTER TASK TASKDB.DWH.POPULATE_DIM_REVIEWS_RESULTS SUSPEND;
ALTER TASK TASKDB.DWH.POPULATE_FACT_REVENUES SUSPEND;
*/