USE ROLE OPS;

CREATE WAREHOUSE IF NOT EXISTS adhoc_wh
     COMMENT = 'this is adhoc warehosue for all adhoc & development activities'
     WAREHOUSE_SIZE = 'X-SMALL'
     AUTO_RESUME = TRUE
     AUTO_SUSPEND = 60
     ENABLE_QUERY_ACCELERATION = FALSE
     WAREHOUSE_TYPE = 'STANDARD'
     MIN_CLUSTER_COUNT = 1
     MAX_CLUSTER_COUNT = 1
     SCALING_POLICY = 'STANDARD'
     INITIALLY_SUSPENDED = TRUE;
GRANT OPERATE ON WAREHOUSE adhoc_wh TO ROLE ANA;
GRANT USAGE ON WAREHOUSE adhoc_wh TO ROLE ANA;

CREATE WAREHOUSE IF NOT EXISTS load_wh
     COMMENT = 'this is load warehosue for loading files'
     WAREHOUSE_SIZE = 'X-SMALL'
     AUTO_RESUME = TRUE
     AUTO_SUSPEND = 60
     ENABLE_QUERY_ACCELERATION = FALSE
     WAREHOUSE_TYPE = 'STANDARD'
     MIN_CLUSTER_COUNT = 1
     MAX_CLUSTER_COUNT = 1
     SCALING_POLICY = 'STANDARD'
     INITIALLY_SUSPENDED = TRUE;
GRANT OPERATE, USAGE ON WAREHOUSE load_wh TO ROLE DEV;
GRANT OPERATE, USAGE ON WAREHOUSE load_wh TO ROLE SER;

CREATE WAREHOUSE IF NOT EXISTS transform_wh
     COMMENT = 'this is etl warehosue for all loading activity'
     WAREHOUSE_SIZE = 'X-SMALL'
     AUTO_RESUME = TRUE
     AUTO_SUSPEND = 60
     ENABLE_QUERY_ACCELERATION = FALSE
     WAREHOUSE_TYPE = 'STANDARD'
     MIN_CLUSTER_COUNT = 1
     MAX_CLUSTER_COUNT = 1
     SCALING_POLICY = 'STANDARD'
     INITIALLY_SUSPENDED = TRUE;
GRANT OPERATE, USAGE ON WAREHOUSE transform_wh TO ROLE DEV;

CREATE WAREHOUSE IF NOT EXISTS out_wh
     COMMENT = 'this is streamlit and out tables warehouse'
     WAREHOUSE_SIZE = 'X-SMALL'
     AUTO_RESUME = TRUE
     AUTO_SUSPEND = 600
     ENABLE_QUERY_ACCELERATION = FALSE
     WAREHOUSE_TYPE = 'STANDARD'
     MIN_CLUSTER_COUNT = 1
     MAX_CLUSTER_COUNT = 1
     SCALING_POLICY = 'STANDARD'
     INITIALLY_SUSPENDED = TRUE;
GRANT OPERATE, USAGE ON WAREHOUSE out_wh TO ROLE ANA;

CREATE WAREHOUSE IF NOT EXISTS public_wh
     COMMENT = 'public warehouse'
     WAREHOUSE_SIZE = 'X-SMALL'
     AUTO_RESUME = TRUE
     AUTO_SUSPEND = 600
     ENABLE_QUERY_ACCELERATION = FALSE
     WAREHOUSE_TYPE = 'STANDARD'
     MIN_CLUSTER_COUNT = 1
     MAX_CLUSTER_COUNT = 1
     SCALING_POLICY = 'STANDARD'
     INITIALLY_SUSPENDED = TRUE;
GRANT OPERATE, USAGE ON WAREHOUSE public_wh TO ROLE PUBLIC;
