USE ROLE OPS;
CREATE DATABASE IF NOT EXISTS taskdb;
GRANT OWNERSHIP ON DATABASE taskdb TO ROLE DEV;

USE ROLE DEV;
GRANT USAGE ON DATABASE taskdb TO ROLE PUBLIC;
GRANT OWNERSHIP ON SCHEMA taskdb.public TO ROLE ANA;

USE ROLE DEV;
CREATE SCHEMA IF NOT EXISTS taskdb.stg;
GRANT USAGE ON SCHEMA taskdb.stg TO ROLE SER;

USE ROLE DEV;
CREATE SCHEMA IF NOT EXISTS taskdb.dwh;
GRANT USAGE ON SCHEMA taskdb.dwh TO ANA;
GRANT SELECT ON ALL TABLES IN SCHEMA taskdb.dwh TO ANA;
GRANT SELECT ON ALL VIEWS IN SCHEMA taskdb.dwh TO ANA;
USE ROLE OPS; -- I didn't put a note but I think it was neccessary for future objcts.
GRANT SELECT ON FUTURE TABLES IN SCHEMA taskdb.stg TO ANA;
GRANT SELECT ON FUTURE TABLES IN SCHEMA taskdb.dwh TO ANA;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA taskdb.dwh TO ANA;

USE ROLE DEV;
CREATE SCHEMA IF NOT EXISTS taskdb.out;
GRANT OWNERSHIP ON SCHEMA taskdb.out TO ROLE ANA;


USE ROLE ANA;
GRANT USAGE ON SCHEMA taskdb.public TO PUBLIC;
USE ROLE OPS;
GRANT SELECT ON ALL VIEWS IN SCHEMA taskdb.public TO PUBLIC;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA taskdb.public TO PUBLIC;