USE ROLE useradmin;
CREATE USER de_mw PASSWORD = '123' DEFAULT_ROLE = dev MUST_CHANGE_PASSWORD = TRUE;
USE ROLE securityadmin;
GRANT ROLE OPS to USER de_mw;

USE ROLE useradmin;
CREATE USER robot PASSWORD = '123' DEFAULT_ROLE = ser MUST_CHANGE_PASSWORD = TRUE;
USE ROLE securityadmin;
GRANT ROLE ser to USER robot;

USE ROLE useradmin;
CREATE USER test PASSWORD = '123' DEFAULT_ROLE = public MUST_CHANGE_PASSWORD = TRUE;

USE ROLE useradmin;
CREATE USER de_ms PASSWORD = '123' DEFAULT_ROLE = dev MUST_CHANGE_PASSWORD = TRUE;
USE ROLE securityadmin;
GRANT ROLE DEV to USER de_ms;